import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { ThemeProvider } from "@/components/provider/theme-provider";

import { TooltipProvider } from "@/components/ui/tooltip"
import ModalProvider from "@/components/provider/modal-provider";
const font = Open_Sans({
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={font.className}
        >
          <ModalProvider/>
           <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey="message-app"
          >
            <TooltipProvider>{children}</TooltipProvider>
            
          </ThemeProvider>
         
        </body>
      </html>
    </ClerkProvider>
  );
}
